### ISSUE TITLE
Не обрабатывает корректно ctrl-c в процессе настройки

### ISSUE THREAD

**Issue by vvzvlad** [hazzus/liker-group-script#12]
При прерывании в процессе настройки некрасиво падает. Можно KeyboardInterrupt обработать корректно? 

```
Max likes on user page("inf" for infinity): ^CTraceback (most recent call last):
  File "main.py", line 144, in <module>
    info = WorkInformation()
  File "/Users/vvzvlad/Downloads/тест/information.py", line 28, in __init__
    self.get_information_from_user()
  File "/Users/vvzvlad/Downloads/тест/information.py", line 111, in get_information_from_user
    self.likes_amount = input('Max likes on user page("inf" for infinity): ')
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 153, in <module>
    if info is not None:
NameError: name 'info' is not defined
```

**Comment by hazzus** [comment]
fixed, due to another type of configuration now
